# docker compose up -d
networks:
  default:
    name: ${APP_NET-env}
    external: true

services:
  app:
    image: xampp/php:8.4
    hostname: ${APP_DOMAIN-${COMPOSE_PROJECT_NAME}.app.localhost}
    volumes:
      - .:/app
    command: -S 0.0.0.0:80 -t public
    ports:
      - "${APP_PORT:-}:80"
    environment:
      APP_ENV: ${APP_ENV-dev}
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=443
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${APP_DOMAIN-${COMPOSE_PROJECT_NAME}.app.localhost}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls.certresolver=letsencrypt
