# docker compose up -d
networks:
  default:
    name: ${ENV_NET_NAME:-env}
    external: true

services:
  app:
    image: php:8.4
    hostname: ${APP_URL:-${COMPOSE_PROJECT_NAME}.app.localhost}
    working_dir: /app
    volumes:
      - .:/app
    command: -S 0.0.0.0:80 -t public
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=443
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${APP_URL:-${COMPOSE_PROJECT_NAME}.app.localhost}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls.certresolver=letsencrypt
