# docker compose up -d
services:
  app:
    image:  php:8.4-cli
    volumes:
      - .:/app
    command: php -S 0.0.0.0:8000 -t public
    user: 1000:1000
    ports:
      - "8000:8000"
    working_dir: /app